<?php

namespace common\models;

use Yii;
use yii\helpers\ArrayHelper;

/**
 * This is the model class for table "blog".
 *
 * @property int $id
 * @property string $title
 * @property string $text
 * @property string $url
 * @property int $status_id
 * @property int $sort
 */
class Blog extends \yii\db\ActiveRecord
{
    public $tags_array;

    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'blog';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['title', 'url'], 'required'],
            [['text'], 'string'],
            [['url'], 'unique'],
            [['title', 'url'], 'string', 'max' => 150],
            [['status_id'], 'integer', 'max' => 9],
            [['sort'], 'integer', 'max' => 99, 'min' => 1],
            [['tags_array'], 'safe'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'title' => 'Заголовок',
            'text' => 'Текст',
            'url' => 'ЧПУ',
            'status_id' => 'Статус',
            'sort' => 'Sort',
            'tags_array' => 'Тэги',
            'tagsAsString' => 'Тэги',
            'author.username' => 'Имя автора',
            'author.email' => 'Почта автора',
        ];
    }

    public static function getStatusList()
    {
        return ['off', 'on'];
    }

    public function getStatusName()
    {
        $list = self::getStatusList();
        return $list[$this->status_id];
    }

    public function getAuthor()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }

    public function getBlogTags()
    {
        $blogTags  = $this->hasMany(BlogTag::className(), ['blog_id' => 'id']);
        return $blogTags;
    }

    public function getTags()
    {
        return $this->hasMany(Tag::className(), ['id' => 'tag_id'])->via('blogTags');
    }

    public function afterFind()
    {
        $this->tags_array = $this->tags;
    }

    public function getTagsAsString()
    {
        $arr = ArrayHelper::map($this->tags, 'id', 'name');
        return implode(', ', $arr);
    }

    public function afterSave($insert, $changedAttributes)
    {
        parent::afterSave($insert, $changedAttributes); // TODO: Change the autogenerated stub

        $arr = \yii\helpers\ArrayHelper::map($this->tags, 'id', 'id');
        foreach($this->tags_array as $one)
        {
            // если в массиве $arr нет элемента в массиве полученного из селекта формы, то создаем новую запись
            if(!in_array($one, $arr)){
                $model = new BlogTag();
                $model->blog_id = $this->id;
                $model->tag_id = $one;
                $model->save();
            }
            // в массиве $arr останутся только те элементы массива, которые не были выбраны в селекте
            if(isset($arr[$one])){
                unset($arr[$one]);
            }
        }
        // удаление всех записей БД по условию "'tag_id' => $arr"
        BlogTag::deleteAll(['tag_id' => $arr]);
    }
}
